### ISSUE TITLE
Username @mrcll

### ISSUE THREAD

**Issue by pormarcelle** [pormarcelle/hello-mrcll#1]
Hello, @mrcll. How are you? I hope you're doing okay. Well, I tried to get in touch with you through an e-mail address, but I couldn't find any. Anyway, my name is Marcelle and the reason I wanted to talk to you is that I'm renaming all my usernames to "mrcll" and since you're not very active on GitHub, I was wondering if you could hand me your username for my personal use. Could you please do this favor for me? I'd be forever grateful. I will be waiting for your answer. Thank you in advance.

Ps¹: I'm sorry if I'm being inconvenient. I hope I didn't take much of your time.
Ps²: Apologies for any grammar mistakes. English is not my native language.

**Comment by mrcll** [comment]
Dear Marcelle,
I'm really sorry, I'm afraid I can't change my username, because I actively use it in private repositories and I use a few websites too, where I login with this profile.
Thank you for your understanding.

**Comment by pormarcelle** [comment]
Oh, I did not know you had private repositories. No worries! I totally understand you. Thank you for taking the time to talk to me, @mrcll. I really appreciate it. Have a nice week! :blush:
